apiVersion: v1
kind: Service
metadata:
  name: svc-devops2026
spec:
  type: NodePort
  selector:
    app: tarefa
  ports:
    - name: http
      port: 8000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops2026
  labels:
    app: tarefa
spec:
  selector:
    matchLabels:
      app: tarefa
  template:
    metadata:
      labels:
        app: tarefa
    spec:
      containers:
        - name: tarefa
          image: suethkiu/devopsdocker:latest
          ports:
            - containerPort: 8000
              name: http
