name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch: 

jobs:
  testes_unitarios:
    name: "Integração"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalação de dependências
        run: pip install -r requirements.txt
      - name: Testes unitários
        run: pytest
